language: python
python:
  - "2.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran libatlas-base-dev
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.pip --use-mirrors
script: nosetests
notifications:
  irc: "irc.freenode.org#modilabs"
